#%RAML 1.0 Library
usage: post-firstcoach-reservation-Type

types: 
  Schedules:
      properties:
        originLocation:
          type: LocationCode
        destinationLocation:
          type: LocationCode

  LocationCode:
    properties:
      locationCode: 
        type: string
      


      
    
      