#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/64b504a0-c518-420b-9bae-49fc5d65c98f/ # 
title: external-firstcoach-system
version: v1
description: API for External FirstCoach Routes and Schedules. 
mediaType: application/json

uses:
  schedules: libraries/fetchschedules.raml

/fetchSchedules:
  post:
    description: To fetch shcedules
    body:
      application/json:
        type: schedules.Schedules
        example:
          !include examples/post-fetchschedules-request.json
    responses:
      200:
        body:
          example:
            !include examples/post-fetchschedules-response.json

/fetchRoutes:
    get: 
        description: To Fetch Routes
        responses:
          200:
            body:
              example: !include examples/get-fetchroutes-response.json 
